export const mockEnvironmentsResponse = [
  {
    id: "d5d7c445-46bf-4335-a0bb-cf0600c68768",
    name: "benchScape-main-mac-14",
    description: "BenchScape main branch on MacOS",
    gitOriginUrl: null,
    gitBranch: null,
    systemArch: null,
    systemProcessors: 0,
    systemProcessorsMin: null,
    systemProcessorsMax: null,
    systemMemory: null,
    systemMemoryMin: null,
    systemMemoryMax: null,
    systemMemoryReadable: null,
    systemMemoryMinReadable: null,
    systemMemoryMaxReadable: null,
    osName: "Mac OS X",
    osVersion: "14.1.1",
    osFamily: "MAC_OS",
    jvmVersion: "",
    jvmName: null,
    jmhVersion: "",
  },
  {
    id: "4ad2afeb-9617-4b44-bbc4-342fd5937d3d",
    name: "benchScape-main-mac-13",
    description: "BenchScape main branch on MacOS",
    gitOriginUrl: "https://github.com/OpenElements/BenchScape",
    gitBranch: "main",
    systemArch: null,
    systemProcessors: null,
    systemProcessorsMin: null,
    systemProcessorsMax: null,
    systemMemory: null,
    systemMemoryMin: null,
    systemMemoryMax: null,
    systemMemoryReadable: null,
    systemMemoryMinReadable: null,
    systemMemoryMaxReadable: null,
    osName: "Mac OS X",
    osVersion: "13.0.0",
    osFamily: "MAC_OS",
    jvmVersion: null,
    jvmName: null,
    jmhVersion: null,
  },
  {
    id: "09023de3-4cf1-4e7a-bc5b-dcd55b189564",
    name: "benchScape-main-win",
    description: "BenchScape main branch on Windows",
    gitOriginUrl: "https://github.com/OpenElements/BenchScape",
    gitBranch: "main",
    systemArch: null,
    systemProcessors: null,
    systemProcessorsMin: null,
    systemProcessorsMax: null,
    systemMemory: null,
    systemMemoryMin: null,
    systemMemoryMax: null,
    systemMemoryReadable: null,
    systemMemoryMinReadable: null,
    systemMemoryMaxReadable: null,
    osName: "Windows",
    osVersion: null,
    osFamily: "WINDOWS",
    jvmVersion: null,
    jvmName: null,
    jmhVersion: null,
  },
];

export const mockEnvironment = {
  id: "some-uuid",
  name: "benchScape-mock-win",
  description: "BenchScape mock Windows",
  gitOriginUrl: "https://github.com/OpenElements/BenchScape",
  gitBranch: "main",
  systemArch: null,
  systemProcessors: null,
  systemProcessorsMin: null,
  systemProcessorsMax: null,
  systemMemory: null,
  systemMemoryMin: null,
  systemMemoryMax: null,
  systemMemoryReadable: null,
  systemMemoryMinReadable: null,
  systemMemoryMaxReadable: null,
  osName: "Windows",
  osVersion: null,
  osFamily: "WINDOWS",
  jvmVersion: null,
  jvmName: null,
  jmhVersion: null,
};
